spring.datasource.url: jdbc:mysql://localhost:3306/test_db
spring.datasource.username: root
spring.datasource.password: 21213Pav333+
spring.jpa.show-sql: false
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddl-auto: validate
spring.flyway.locations: classpath:db.migration
spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.max-request-size: 50MB
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: alexei0963@gmail.com
spring.mail.password: dsvwgjybpmsyrftm
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 917 333-44-55
blog.email: dmitry-mail@gmail.com
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2020

upload.path: /upload
userPhotos.path: /users photos

